# -*- coding: utf-8 -*-
"""Streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ac-qzCd-ouxvLuBNCTNx9VPBKVwvSYFq
"""

import streamlit as st

st.title ("Machine Learning Project")



st.header("Regression model tutorial")
st.subheader("Definition of regression model")
st.text("hello shhdj")
st.markdown("ABCDE")